### ISSUE TITLE
When the number of esims in the card is greater than one, the card information cannot be loaded.

### ISSUE THREAD

**Issue by chx818** [Truphone/LPAdesktop#6]
The specific performance is that the software interface will be stuck, and processing will always be displayed. The log is as follows
C:\Users\chx81\Downloads\lpa>java -jar LPA-1.0.0.0-jar-with-dependencies.jar
Feb 24, 2023 10:29:38 pm com.truphone.lpap.LPAUI <init>
Information: STARTING
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Info: Send Terminal Capabilities
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: 80aa00000aa9088100820101830107
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: 0x9000
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: Open Logical Channel and Select ISD-R
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: 00a4040010a0000005591010ffffffff8900000100
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: 0x9000
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: Send Status
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Info: 80f2000c00
Feb 24, 2023 10:29:43 pm com.truphone.lpap.card.ApduChannelImpl <init>
Information: 0x9000
Feb 24, 2023 10:29:43 pm com.truphone.lpa.impl.LocalProfileAssistantImpl <init>
Information: - SM-DP connection initiated.
Feb 24, 2023 10:29:43 pm com.truphone.util.LogStub logDebug
Information: - Getting Profiles
Feb 24, 2023 10:29:43 pm com.truphone.util.LogStub logDebug
Information: List profiles APDU: 81E2910003BF2D00
Feb 24, 2023 10:29:44 pm com.truphone.lpa.impl.ListProfilesWorker run
Severe: - Unexpected end of sequence, length tag: 112, actual sequence length: 73
java.io.IOException: Unexpected end of sequence, length tag: 112, actual sequence length: 73
         at com.truphone.rsp.dto.asn1.rspdefinitions.ProfileInfo.decode(ProfileInfo.java:537)
         at com.truphone.rsp.dto.asn1.rspdefinitions.ProfileInfoListResponse$ProfileInfoListOk.decode(ProfileInfoListResponse.java:102)
         at com.truphone.rsp.dto.asn1.rspdefinitions.ProfileInfoListResponse.decode(ProfileInfoListResponse.java:246)
         at com.truphone.rsp.dto.asn1.rspdefinitions.ProfileInfoListResponse.decode(ProfileInfoListResponse.java:229)
         at com.truphone.lpa.impl.ListProfilesWorker.decodeProfiles(ListProfilesWorker.java:74)
         at com.truphone.lpa.impl.ListProfilesWorker.run(ListProfilesWorker.java:37)
         at com.truphone.lpa.impl.LocalProfileAssistantImpl.getProfiles(LocalProfileAssistantImpl.java:95)
         at com.truphone.lpap.LpaSrc.getProfiles(LpaSrc.java:57)
         at com.truphone.lapp.LPAUI.listProfiles(LPAUI.java:810)
         at com.truphone.lapp.LPAUI.access$1800(LPAUI.java:55)
         at com.truphone.lapp.LPAUI$18.doInBackground(LPAUI.java:590)
         at javax.swing.SwingWorker$1.call(Unknown Source)
         at java.util.concurrent.FutureTask.run(Unknown Source)
         at javax.swing.SwingWorker.run(Unknown Source)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
         at java.lang.Thread.run(Unknown Source)

**Comment by XIAZY** [comment]
Looks like an upstream problem, probably worth looking into
https://github.com/Truphone/LPAd_SM-DPPlus_Connector/blob/master/lpad-sm-dp-plus-connector/src/main/java/com/truphone/lpa/impl/ListProfilesWorker.java#L74

**Comment by XIAZY** [comment]
Looks like this ASN file isn't defined well or is outdated
https://github.com/Truphone/LPAd_SM-DPPlus_Connector/blob/24ce93a07f15044e1d8d6a5e1ee3aff8eb1b4210/lpad-sm-dp-plus-connector/src/main/resources/rsp.asn

**Comment by XIAZY** [comment]
Looks like the ASN file isn't maintained well or is outdated
https://github.com/Truphone/LPAd_SM-DPPlus_Connector/blob/24ce93a07f15044e1d8d6a5e1ee3aff8eb1b4210/lpad-sm-dp-plus-connector/src/main/resources/rsp.asn
While I'm not a telecom exprrt, maybe someone else can update this file

**Comment by XIAZY** [comment]
Actually, this has been fixed by PR https://github.com/Truphone/LPAd_SM-DPPlus_Connector/pull/9
Confirmed to be working with this LPADesktop project

**Comment by qingz2004** [comment]
How can I get the fix? I recompiled LPAdesktop, still the same problem.

**Comment by XIAZY** [comment]
Recompilation should fix the problem, chances are you don't have the updated dependencies.
But honestly even if you do there are other problems as well, like enabling profiles, I'm getting non GSMA defined behaviour

**Comment by qingz2004** [comment]
I think you are right. How can I get the updated dependencies?

**Comment by XIAZY** [comment]
> I think you are right. How can I get the updated dependencies?

Just use this branch and recompile https://github.com/Truphone/LPAd_SM-DPPlus_Connector/pull/9
Unfortunately Truphone appears to have stopped maintaining these projects, which is sad

**Comment by qingz2004** [comment]
That works. I can now list the profile now.
Thanks!

**Comment by qingz2004** [comment]
I can only list the profiles, sometimes I can disable a profile, but not able to enable a profile. Didn't try delete profile yet.

**Comment by XIAZY** [comment]
> I can only list the profiles, sometimes I can disable a profile, but not able to enable a profile. Didn't try delete profile yet.

Yea, it doesn't work. I looked into it, reason is getting non GSMA defined response codes from SMART card reader.
So im guessing either the card I use isn't compliant or the software doesn't handle such responses. Either way I have gave up
